
document.getElementById('startBtn').addEventListener('click', async () => {
    const statusEl = document.getElementById('status');
    const startBtn = document.getElementById('startBtn');
    const resultsArea = document.getElementById('resultsArea');
    const inputsList = document.getElementById('inputsList');
    
    startBtn.disabled = true;
    resultsArea.classList.add('hidden');
    statusEl.innerText = 'Scanning page inputs...';
  
    try {
      // 1. Get the current active tab
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      
      if (!tab) {
        throw new Error("No active tab found");
      }
  
      // 2. Request inputs from content script
      const response = await chrome.tabs.sendMessage(tab.id, { action: "LIST_PAGE_INPUTS" });
      
      if (!response || !response.success || response.data.length === 0) {
        statusEl.innerText = 'No inputs found on this page.';
        startBtn.disabled = false;
        return;
      }
  
      // 3. Mock AI Processing
      statusEl.innerText = `Found ${response.data.length} inputs. Asking AI...`;
      
      const aiResponse = await mockAskLLM(response.data);
      
      // 4. Render results
      renderResults(aiResponse);
      
      statusEl.innerText = 'Analysis complete.';
      resultsArea.classList.remove('hidden');
      
      // Store data for filling
      document.getElementById('fillBtn').onclick = () => fillPage(tab.id, aiResponse);
  
    } catch (err) {
      console.error(err);
      statusEl.innerText = 'Error: ' + err.message;
    } finally {
      startBtn.disabled = false;
    }
  });
  
  async function fillPage(tabId, dataWithValues) {
    const statusEl = document.getElementById('status');
    statusEl.innerText = 'Filling inputs...';
    try {
      const resp = await chrome.tabs.sendMessage(tabId, { 
        action: "FILL_PAGE_INPUTS", 
        data: dataWithValues 
      });
      statusEl.innerText = `Success! Filled ${resp.count} fields.`;
    } catch (err) {
      statusEl.innerText = 'Fill Error: ' + err.message;
    }
  }
  
  function renderResults(data) {
    const container = document.getElementById('inputsList');
    container.innerHTML = '';
    
    data.forEach(item => {
      const div = document.createElement('div');
      div.className = 'input-item';
      div.innerHTML = `
        <label>${item.label || item.name || item.id}</label>
        <div class="val-preview">AI: "${item.value}"</div>
      `;
      container.appendChild(div);
    });
  }
  
  // === MOCK LLM FUNCTION ===
  // In a real app, this would call an API like OpenAI
  async function mockAskLLM(inputs) {
    return new Promise(resolve => {
      setTimeout(() => {
        const enriched = inputs.map(input => {
          let aiValue = "Auto-Filled";
          
          // Simple rule-based generation for demo
          const lowerName = (input.name + input.label + input.id).toLowerCase();
          
          if (lowerName.includes('email')) aiValue = "user@sharkbook.com";
          else if (lowerName.includes('name')) aiValue = "Sharky User";
          else if (lowerName.includes('phone') || lowerName.includes('tel')) aiValue = "555-0199";
          else if (lowerName.includes('address')) aiValue = "123 Ocean Drive, Deep Sea";
          else if (lowerName.includes('city')) aiValue = "Atlantis";
          else if (lowerName.includes('zip')) aiValue = "10001";
          else if (lowerName.includes('company')) aiValue = "Shark Corp";
          else if (lowerName.includes('date')) aiValue = "2023-10-01";
          else if (input.tag === 'textarea') aiValue = "This is a comment generated by Sharkbook AI assistant.";
          
          return { ...input, value: aiValue };
        });
        resolve(enriched);
      }, 1500); // Simulate network delay
    });
  }
